# Generated by Django 4.2.7 on 2024-04-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('birthdate', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('birthdate', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('numberPhone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('OrderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CreationDate', models.CharField(max_length=30)),
                ('IdDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.employees')),
                ('IdPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('reasonConsultation', models.CharField(max_length=30)),
                ('symptoms', models.CharField(max_length=30)),
                ('diagnosis', models.CharField(max_length=30)),
                ('procedure', models.CharField(max_length=30)),
                ('procedureDetail', models.CharField(max_length=30)),
                ('medicine', models.CharField(max_length=30)),
                ('medicineDose', models.CharField(max_length=30)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.employees')),
            ],
        ),
    ]
